/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBackground: typeof import('./src/components/AppBackground.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppBarCopy: typeof import('./src/components/AppBarCopy.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CardWrapper: typeof import('./src/components/CardWrapper.vue')['default']
    GameCard: typeof import('./src/components/GameCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LangSwitcher: typeof import('./src/components/LangSwitcher.vue')['default']
    LanguageAppBar: typeof import('./src/components/LanguageAppBar.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    MapAttributions: typeof import('./src/components/MapAttributions.vue')['default']
    MapBackground: typeof import('./src/components/MapBackground.vue')['default']
    MapGpsControls: typeof import('./src/components/MapGpsControls.vue')['default']
    MapZoomControls: typeof import('./src/components/MapZoomControls.vue')['default']
    ProjectInfoDialog: typeof import('./src/components/ProjectInfoDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
